logger:
  level: "debug"

server:
  port: 8080

mongo:
  host: "localhost"
  port: 27017
  database: "image"
  direct-connection: true

kafka:
  brokers: "localhost:9092"
  consumers-config:
    group-id: "ecommerce-image-service"
    auto-offset-reset: "earliest"
    consumers:
      - handler: "productCreatedHandler"
        topic: "catalog.product.created.v1"
      # - handler: "productUpdatedHandler"
      #   topic: "catalog.product.updated.v1"

observability:
  tracing-enabled: true
  metrics-enabled: false
  otel-collector-endpoint: ""

application:
  presign-ttl: 15m # Presigned URL validity duration
  max-upload-bytes: 5242880 # 5 MB - maximum upload size

s3:
  endpoint: "http://localhost:9000"
  public-endpoint: "http://localhost:9000"
  region: "us-east-1"
  bucket: "products"
  access-key-id: "minioadmin"
  secret-key: "minioadmin123"
  use-path-style: true

imgproxy:
  base-url: "http://localhost:8081"
  key-hex: "0000000000000000000000000000000000000000000000000000000000000000"
  salt-hex: "1111111111111111111111111111111111111111111111111111111111111111"
